





ricedict = {'beer bike': 'BEEEEEEEEEEER BIKE!!!!! One of the few events of the year',
     'rpc': 'Rice Program Council. They host events like Screw-Yer-Roommate and Esperanza',
    'rmc': 'Rice Memorical Center aka Student Center aka Coffeehouse',
'rec': 'Place to go workout',
'chug team': 'Those who chug at Beer Bike',
'bike team': 'Those who bike at Beer Bike',
'premed': 'They care about their grades. Hoping to get into medical school one day.',
'Alcohol Policy': 'A joke. Rice has wet campus policy so beer and wine arent judged harshly. Just dont',
'CHBE': 'Chemical engineering major. Sucks to suck!',
'Chubby': 'Chemical engineering major. Sucks to suck!',
'BIOE': 'Bioengineering major. May or may not have once been a premed.',
'Orgo': 'Organic Chemistry, a.k.a. Something that makes your sophomore year hell, or freshman (if youre trying really hard).',
'Public': 'A hot sweaty mess held in some colleges commons. Notable ones include Night of Decadence.',
'Private': 'Lots of drinking in one location',
'Crawl': 'Lots of drinking in various locations',
'SA': 'Resume boost- the Student Association of Rice who are responsible for passing (mostly pointless) legislation',
'Fuck Will Rice': 'Seriously, Fuck those dudes',
'Leebron': 'Does not smile a lot. President of Rice, but wishes he were at Harvard.',
'Leebs': 'Does not smile a lot. President of Rice, but wishes he were at Harvard.',
'Hutch': 'former dean of undergrads, smiles a lot',
'WRC': 'Will Rice College',
'JIBA': 'Jones Is Bad Ass',
'BSWB': 'Brown, Shit We\'re Bad',
'MBYM': 'Martel Bangs Your Mom',
'EOL RRF': 'Edgar Odell Lovett, Rah Rah Fuck',
'Pub': 'Hot n sweaty on Thursday nights. Great place to grab a cheap beer',
'Willy\'s': 'Refers to pub, but can also refer to the statue in the quad',
'Willy Week': 'When day-drinking is acceptable. Also the week before Beer Bike',
'Fondy': 'Fondren Library, where your dreams go to die',
'Club Fondy': 'A nicer name for Fondren Library',
'Chaus': 'the hipster way of referring to Coffeehouse',
'Coffeehouse': 'Student run business where some students hang out more than their own college',
'The Hoot': 'slightly stale Dominoes that comes in clutch on late nights. Also has honey butter biscuits',
'Sammy\'s': 'restaurant in RMC that sells sandwiches',
'East West': 'Boba place. Heaven for most Rice students.',
'Comp': 'Computer science majors call themselves comp to sound cool. You should probably do it too',
'Luay': 'God',
'Comp 182': 'Hell',
'Rixner': 'Most agressive professor',
'Grind': 'Never stops...',
'Bacc': 'Toga party at Brown.',
'Sallyport': 'Big arch at the front of school. Martel also has one.',
'Sundeck': 'Martel has one, the others dont',
'Baker': 'Old college',
'Lovett': 'Bomb proof toaster',
'Sid Rich': 'Sid Richardson',
'Sid Richardson': 'about to be remodeled. Good riddance.',
'SRC': 'Sid Richardson College',
'Duncan': 'see McMurtry college',
'McMurtry': 'see Duncan college',
'Will Rice': 'im sorry did you mean fuck will rice?',
'Hanszen': 'Apparently theyre friendly',
'Wiess': 'cult',
'Martel': 'best college',
'Jones': 'pretty mediocre. They blow goats. Johnny Cai is here.',
'Brown': 'Brown is shit',
'Esperanza': 'Dance hosted by RPC',
'Rondelet': 'Spring formal dance',
'Nod': 'Night of Decadence',
'Night of Decadence': 'Party at Wiess -- historically ranked one of the best by Forbes',
'Evening of Elegance': 'alternative to Nod',
'Purity Test': 'your entire time at Rice is determined by how you respond to this survey',
'Thresher': 'Campus newspaper. Prints 3-5 controversial op-eds each year. #FakeNews.',
'OEDK': 'Oshman Engineering Design Kitchen. ENGI classroom and makerspace.',
'Hack Rice': 'Fun comp competition',
'CJ': 'Chief Justice. Stick up their ass.',
'AJ': 'Associate Justices. Literally have no duties.'}
